"""
Pydantic models for resolution plans and DSL steps.
"""

from enum import Enum
from typing import Optional, List, Any, Dict
from pydantic import BaseModel, Field, ConfigDict


class StepType(str, Enum):
    """Enumeration of resolution step types."""
    VERIFY_CHARGE = "verify_charge"
    APPLY_CREDIT = "apply_credit"
    ISSUE_REFUND = "issue_refund"
    NOTIFY_CUSTOMER = "notify_customer"
    ESCALATE_TO_HUMAN = "escalate_to_human"
    CREATE_AUDIT_LOG = "create_audit_log"
    CHECK_POLICY = "check_policy"
    CALCULATE_AMOUNT = "calculate_amount"
    UPDATE_BILLING_RECORD = "update_billing_record"
    SEND_CONFIRMATION = "send_confirmation"


class StepStatus(str, Enum):
    """Enumeration of resolution step execution statuses."""
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ResolutionStep(BaseModel):
    """
    Pydantic model representing a single step in a resolution plan DSL.
    
    This is a structured, executable unit generated by Layer 3 (Resolution Plan Generation).
    Each step has preconditions, can execute deterministically, and produces expected output
    that feeds into subsequent steps.
    """
    
    step_id: int = Field(
        ...,
        ge=1,
        description="Unique identifier for this step within the resolution plan"
    )
    
    step_type: StepType = Field(
        ...,
        description="Type of action to execute (e.g., verify_charge, apply_credit)"
    )
    
    preconditions: List[str] = Field(
        default_factory=list,
        description="List of conditions that must be true before this step executes. "
                    "Conditions reference outputs from previous steps (e.g., 'verification_result.chargeIsErroneous == true')"
    )
    
    expected_output: str = Field(
        ...,
        description="Description of the expected output/result after successful execution"
    )
    
    status: StepStatus = Field(
        default=StepStatus.PENDING,
        description="Current execution status of this step"
    )
    
    parameters: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Step-specific parameters passed to the executor"
    )
    
    model_config = ConfigDict(
        use_enum_values=False,
        json_schema_extra={
            "example": {
                "step_id": 1,
                "step_type": "verify_charge",
                "preconditions": ["invoice must exist"],
                "expected_output": "Verification result with chargeIsErroneous flag",
                "status": "PENDING",
                "parameters": {
                    "invoiceId": "INV-2026-04-001",
                    "checkUsageLogs": True
                }
            }
        }
    )


class ResolutionPlan(BaseModel):
    """
    Pydantic model representing a complete resolution plan DSL.
    
    Generated by Layer 3, containing an ordered sequence of steps that will be
    executed sequentially by Layer 4 (Deterministic Execution Engine).
    """
    
    plan_id: str = Field(
        ...,
        description="Unique identifier for this resolution plan"
    )
    
    dispute_id: str = Field(
        ...,
        description="ID of the dispute this plan resolves"
    )
    
    steps: List[ResolutionStep] = Field(
        ...,
        min_items=1,
        description="Ordered list of resolution steps to execute"
    )
    
    estimated_duration_seconds: Optional[float] = Field(
        default=None,
        description="LLM's estimate of execution time for the entire plan"
    )
    
    requires_human_approval: bool = Field(
        default=False,
        description="Whether any step in the plan requires manual human approval before execution"
    )
    
    approval_reason: Optional[str] = Field(
        default=None,
        description="Reason why human approval is required (if needed)"
    )
    
    model_config = ConfigDict(
        use_enum_values=False,
        json_schema_extra={
            "example": {
                "plan_id": "PLAN-2026-04-001",
                "dispute_id": "DISP-2026-04-001",
                "steps": [
                    {
                        "step_id": 1,
                        "step_type": "verify_charge",
                        "preconditions": ["invoice must exist"],
                        "expected_output": "Verification result",
                        "status": "PENDING",
                        "parameters": {"invoiceId": "INV-2026-04-001"}
                    },
                    {
                        "step_id": 2,
                        "step_type": "apply_credit",
                        "preconditions": ["verification_result.chargeIsErroneous == true"],
                        "expected_output": "Credit issued",
                        "status": "PENDING",
                        "parameters": {"amount": 4950.00}
                    },
                    {
                        "step_id": 3,
                        "step_type": "notify_customer",
                        "preconditions": ["credit applied"],
                        "expected_output": "Email sent",
                        "status": "PENDING"
                    }
                ],
                "estimated_duration_seconds": 30,
                "requires_human_approval": False
            }
        }
    )


class StepExecutionResult(BaseModel):
    """
    Model representing the result of executing a single resolution step.
    """
    
    step_id: int = Field(
        ...,
        description="ID of the executed step"
    )
    
    step_type: StepType = Field(
        ...,
        description="Type of step executed"
    )
    
    status: StepStatus = Field(
        ...,
        description="Final execution status"
    )
    
    result: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Output data from step execution"
    )
    
    error_message: Optional[str] = Field(
        default=None,
        description="Error details if execution failed"
    )
    
    execution_time_ms: float = Field(
        default=0.0,
        description="Time taken to execute this step in milliseconds"
    )
    
    model_config = ConfigDict(
        use_enum_values=False,
        json_schema_extra={
            "example": {
                "step_id": 1,
                "step_type": "verify_charge",
                "status": "SUCCESS",
                "result": {
                    "chargeIsErroneous": True,
                    "usageFound": 0,
                    "chargedAmount": 5000.00
                },
                "execution_time_ms": 125.5
            }
        }
    )
